
disabled_rules:
  - redundant_string_enum_value
  - mark
  #- syntactic_sugar
  - generic_type_name
  - empty_enum_arguments
  - comma
  - closing_brace
  - closure_parameter_position
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - line_length
  - large_tuple
  - missing_docs
  - nesting
  - notification_center_detachment
  - opening_brace
  - return_arrow_whitespace
  - statement_position
  - todo
  - trailing_comma
  - type_body_length
  - type_name
  - valid_docs
  - variable_name
  - variable_name_min_length
  - vertical_whitespace
  - vertical_parameter_alignment
  - unused_closure_parameter
included:
  - HobbyApp
excluded:
  - Pods
