osx_image: xcode9.1
language: objective-c
xcode_sdk: iphonesimulator10.3
git:
  depth: 1
cache:
- bundler
- cocoapods
before_install:
- brew update
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone SE (10.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
install:
- gem install bundler
- bundle install
- bundle exec pod repo update --silent
- bundle exec pod install
before_script:
- export LANG=en_US.UTF-8
script:
- gem install danger -v 2.0.1 --no-ri --no-rdoc && danger
- set -o pipefail && travis_retry xcodebuild -workspace HobbyApp.xcworkspace -scheme HobbyApp -configuration
  Debug -destination "id=$IOS_SIMULATOR_UDID" clean test | xcpretty -f `xcpretty-travis-formatter`
notifications:
  email: false